variable "ami" {}
variable "ec2-type" {
  description = "Ec2 Instance Type"
  type=string
  default = "t2.micro"
}
variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}
variable "instance_type" {}
#variable "autoscaling_group_min_size" {}
#variable "autoscaling_group_max_size" {}
